#!/usr/bin/env bash
# git clone --branch dynamic_crop https://github.com/danbider/lightning-pose.git
# cd lightning-pose
# pip install -e .
# pip install lightning-pose==1.6.0

pip install moviepy --upgrade
pip install ffmpeg --upgrade

pip install aind-data-schema==1.1.1
pip install rerun-sdk==0.19.1
set -e

# install updated version of code-server
VERSION=4.20.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -
